apiVersion: v1
kind: Pod
metadata:
  name: ng-pvc 
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: pvc-simple
