kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-simple
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
  labels:
    host: minikube
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mydata"
