kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-simple
  labels:
    host: minikube
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mydata"
