kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-simple
  labels:
    host: minikube
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data
