apiVersion: v1
kind: Pod
metadata:
  name: ng-pod
  labels:
    kind: web
    target: dev
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ngservice
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30101
  selector:
    target: dev
  type: NodePort
